name: ui_kit
description: A demo application for Widgetbook and how to implement a design system from Figma.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  fluttertoast: any
  flutter_easyloading: any
  pull_to_refresh: any
  cached_network_image: any
  flustars: any
  lottie: any
  flutter_svg: any
  flutter_inappwebview: any

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: myIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf
